<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" total="5" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="24367" started-at="2024-10-15T13:55:37Z" finished-at="2024-10-15T13:56:01Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="24367" started-at="2024-10-15T13:55:37Z" finished-at="2024-10-15T13:56:01Z">
      <class name="org.sample.OrderExecution$Rerun">
        <test-method status="PASS" signature="openChrome()[pri:0, instance:org.sample.OrderExecution$Rerun@224edc67]" name="openChrome" is-config="true" duration-ms="2602" started-at="2024-10-15T19:25:37Z" finished-at="2024-10-15T19:25:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openChrome -->
        <test-method status="PASS" signature="starttime()[pri:0, instance:org.sample.OrderExecution$Rerun@224edc67]" name="starttime" is-config="true" duration-ms="6366" started-at="2024-10-15T19:25:39Z" finished-at="2024-10-15T19:25:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- starttime -->
        <test-method status="PASS" signature="logIn()[pri:0, instance:org.sample.OrderExecution$Rerun@224edc67]" name="logIn" duration-ms="291" started-at="2024-10-15T19:25:46Z" finished-at="2024-10-15T19:25:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logIn -->
        <test-method status="PASS" signature="starttime()[pri:0, instance:org.sample.OrderExecution$Rerun@224edc67]" name="starttime" is-config="true" duration-ms="1876" started-at="2024-10-15T19:25:46Z" finished-at="2024-10-15T19:25:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- starttime -->
        <test-method status="PASS" signature="endTime()[pri:0, instance:org.sample.OrderExecution$Rerun@224edc67]" name="endTime" is-config="true" duration-ms="0" started-at="2024-10-15T19:25:46Z" finished-at="2024-10-15T19:25:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTime -->
        <test-method status="SKIP" signature="AgainlogIn()[pri:1, instance:org.sample.OrderExecution$Rerun@224edc67]" name="AgainlogIn" duration-ms="214" started-at="2024-10-15T19:25:48Z" finished-at="2024-10-15T19:25:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Againlogin expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Againlogin expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.sample.OrderExecution$Rerun.AgainlogIn(OrderExecution.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AgainlogIn -->
        <test-method status="PASS" signature="starttime()[pri:0, instance:org.sample.OrderExecution$Rerun@224edc67]" name="starttime" is-config="true" duration-ms="7379" started-at="2024-10-15T19:25:48Z" finished-at="2024-10-15T19:25:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- starttime -->
        <test-method status="PASS" signature="endTime()[pri:0, instance:org.sample.OrderExecution$Rerun@224edc67]" name="endTime" is-config="true" duration-ms="0" started-at="2024-10-15T19:25:48Z" finished-at="2024-10-15T19:25:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTime -->
        <test-method status="SKIP" signature="AgainlogIn()[pri:1, instance:org.sample.OrderExecution$Rerun@224edc67]" name="AgainlogIn" duration-ms="237" started-at="2024-10-15T19:25:55Z" finished-at="2024-10-15T19:25:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Againlogin expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Againlogin expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.sample.OrderExecution$Rerun.AgainlogIn(OrderExecution.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:967)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AgainlogIn -->
        <test-method status="PASS" signature="endTime()[pri:0, instance:org.sample.OrderExecution$Rerun@224edc67]" name="endTime" is-config="true" duration-ms="0" started-at="2024-10-15T19:25:56Z" finished-at="2024-10-15T19:25:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTime -->
        <test-method status="PASS" signature="starttime()[pri:0, instance:org.sample.OrderExecution$Rerun@224edc67]" name="starttime" is-config="true" duration-ms="4312" started-at="2024-10-15T19:25:56Z" finished-at="2024-10-15T19:26:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- starttime -->
        <test-method status="SKIP" signature="AgainlogIn()[pri:1, instance:org.sample.OrderExecution$Rerun@224edc67]" name="AgainlogIn" duration-ms="237" started-at="2024-10-15T19:26:00Z" finished-at="2024-10-15T19:26:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Againlogin expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Againlogin expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.sample.OrderExecution$Rerun.AgainlogIn(OrderExecution.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:967)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AgainlogIn -->
        <test-method status="PASS" signature="endTime()[pri:0, instance:org.sample.OrderExecution$Rerun@224edc67]" name="endTime" is-config="true" duration-ms="0" started-at="2024-10-15T19:26:00Z" finished-at="2024-10-15T19:26:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTime -->
        <test-method status="PASS" signature="starttime()[pri:0, instance:org.sample.OrderExecution$Rerun@224edc67]" name="starttime" is-config="true" duration-ms="631" started-at="2024-10-15T19:26:00Z" finished-at="2024-10-15T19:26:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- starttime -->
        <test-method status="FAIL" signature="AgainlogIn()[pri:1, instance:org.sample.OrderExecution$Rerun@224edc67]" name="AgainlogIn" duration-ms="206" started-at="2024-10-15T19:26:01Z" finished-at="2024-10-15T19:26:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Againlogin expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Againlogin expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.sample.OrderExecution$Rerun.AgainlogIn(OrderExecution.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:967)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AgainlogIn -->
        <test-method status="PASS" signature="endTime()[pri:0, instance:org.sample.OrderExecution$Rerun@224edc67]" name="endTime" is-config="true" duration-ms="0" started-at="2024-10-15T19:26:01Z" finished-at="2024-10-15T19:26:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTime -->
      </class> <!-- org.sample.OrderExecution$Rerun -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
